import SideNav from "@/components/ui/side-nav";
import { Provider } from "@/app/provider";

export const metadata = {
  title: "Werk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Provider> */}
        <body>
          <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
            <div className="w-full flex-none md:w-64">
              <SideNav />
            </div>
            <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
              {children}
            </div>
          </div>
        </body>
      {/* </Provider> */}
    </html>
  );
}
